/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmNovoContratante.java
 *
 * Created on 20/08/2013, 11:56:37
 */
package ui;

import br.diversos.ConverterStringEmItemLista;
import br.GerenciadorLicenca;
import br.diversos.Validacoes;
import br.com.log.LogDinnamus;
import br.com.ui.InteracaoComUsuarioDuranteProcesso;
import br.com.ui.ItemLista;
import br.com.ui.MetodosUI_Auxiliares;
import br.com.ui.frmProgressoTarefa;
import br.entidades.LicencaDadosContratante;
import br.ui.teclas.controleteclas;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Fernando
 */
public class frmNovoContratante extends javax.swing.JDialog {

    /** Creates new form frmNovoContratante */
     private frmProgressoTarefa processamento  =null;
     private  LicencaDadosContratante contratante = new LicencaDadosContratante();
     private boolean bRecarregarComponentes =true;
    public frmNovoContratante(java.awt.Frame parent, boolean modal, LicencaDadosContratante contratante) {
        super(parent, modal);
        this.contratante = (contratante==null ? new LicencaDadosContratante() :  contratante);
        initComponents();        
        setLocationRelativeTo(null);
        controleteclas.TRocarTabPorEnter();
    }
  
    public boolean IniciarUI(){
        try {            
            
            String cUF = contratante.getUf();
            String cCodMunicipio = contratante.getCodmunicipio();
            
            MetodosUI_Auxiliares.PreencherCombo(cbUF, GerenciadorLicenca.UF_Listar(), "nome", "codigo", false,"string","<<ESCOLHA UMA UF>>" );            
            if(contratante.getIdcontratante()==null){                
                cbUF.setSelectedIndex(0);              
            }else{
                bRecarregarComponentes=false;
                MetodosUI_Auxiliares.SetarOpcaoCombo(cbUF, cUF);
                bRecarregarComponentes=true;
                MetodosUI_Auxiliares.PreencherCombo(cbMunicipio, GerenciadorLicenca.UF_MunicipioListar(cbUF.getSelectedItem().toString()), "municipio", "codigo",true);                                                
                MetodosUI_Auxiliares.SetarOpcaoCombo(cbMunicipio, cCodMunicipio);
                txtDataCadastro.setDate(contratante.getData());                      
            }
            if(contratante.getIdcontratante()==null){
                opCPF.requestFocus();                   
            }else{
                if(contratante.getCnpj().trim().length()==14){
                    opCPF.setSelected(true);
                }else{
                    opCNPJ.setSelected(true);
                }
                
            }    
            AtualizarMascara();
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        licencaDadosContratante2 = contratante;
        btIdentificacao = new javax.swing.ButtonGroup();
        DadosContratante = new br.entidades.LicencaDadosContratante();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbUF = new javax.swing.JComboBox();
        cbMunicipio = new javax.swing.JComboBox();
        cbStatus = new javax.swing.JComboBox();
        txtDataCadastro = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        opCPF = new javax.swing.JRadioButton();
        opCNPJ = new javax.swing.JRadioButton();
        txtCNPJ_CPF = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INCLUIR CONTRATANTE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("CODIGO");

        jLabel3.setText("RAZÃO SOC.");

        jLabel4.setText("ENDEREÇO");

        jLabel5.setText("NUMERO");

        jLabel6.setText("BAIRRO");

        jLabel7.setText("MUNICIPIO");

        jLabel9.setText("CEP");

        jLabel10.setText("DT.CONTRATO");

        jLabel11.setText("STATUS");

        txtCodigo.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${idcontratante}"), txtCodigo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${razao}"), txtNome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${cep}"), txtCEP, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${endereco}"), txtEndereco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${numero}"), txtNum, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${bairro}"), txtbairro, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtMunicipio.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${codmunicipio}"), txtMunicipio, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel8.setText("UF");

        cbUF.setModel(new DefaultComboBoxModel<ItemLista>());

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${uf}"), cbUF, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"), "uf");
        binding.setConverter(new ConverterStringEmItemLista());
        bindingGroup.addBinding(binding);

        cbUF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFItemStateChanged(evt);
            }
        });
        cbUF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbUFFocusLost(evt);
            }
        });

        cbMunicipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMunicipioItemStateChanged(evt);
            }
        });
        cbMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbMunicipioFocusGained(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "EXPIRADO", "CANCELADO" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${status}"), cbStatus, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"), "status");
        bindingGroup.addBinding(binding);

        txtDataCadastro.getDateEditor().getUiComponent().addKeyListener(

            new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {}

                @Override
                public void keyPressed(KeyEvent e) {
                    if(e.getKeyCode()==KeyEvent.VK_ENTER){
                        cbStatus.requestFocus();
                    }
                }
                @Override
                public void keyReleased(KeyEvent e) {}

            }
        );
        txtDataCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataCadastroKeyPressed(evt);
            }
        });

        btIdentificacao.add(opCPF);
        opCPF.setSelected(true);
        opCPF.setText("CPF");
        opCPF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opCPFItemStateChanged(evt);
            }
        });

        btIdentificacao.add(opCNPJ);
        opCNPJ.setText("CNPJ");
        opCNPJ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opCNPJItemStateChanged(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${cnpj}"), txtCNPJ_CPF, org.jdesktop.beansbinding.BeanProperty.create("value"), "cnpj");
        bindingGroup.addBinding(binding);

        txtCNPJ_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCNPJ_CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCNPJ_CPFFocusLost(evt);
            }
        });

        jLabel12.setText("NOME FANTASIA");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaDadosContratante2, org.jdesktop.beansbinding.ELProperty.create("${nomefantasia}"), txtNome1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(opCPF)
                .addGap(4, 4, 4)
                .addComponent(opCNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCNPJ_CPF)
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCEP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbairro)
                            .addComponent(txtEndereco)
                            .addComponent(txtNome)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(opCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel8)))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btIncluir.setText("OK");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btFechar)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir)
                    .addComponent(btFechar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    if(!IniciarUI()){
        MetodosUI_Auxiliares.MensagemAoUsuarioSimples(null, "Não foi possível iniciar a interface com usuário", this.getTitle(), "AVISO");
        dispose();
       
    }
}//GEN-LAST:event_formWindowOpened

private void cbUFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFItemStateChanged
// TODO add your handling code here:
     if(bRecarregarComponentes){
        PesquisarMunicipios();
    }
   
}//GEN-LAST:event_cbUFItemStateChanged

private void cbMunicipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMunicipioItemStateChanged
// TODO add your handling code here:
    try {
        
        ItemLista i =(ItemLista)cbMunicipio.getSelectedItem();
        if(i!=null){
            txtMunicipio.setText(i.getIndice().toString());
        }
    } catch (Exception e) {
        LogDinnamus.Log(e, true);
    }
}//GEN-LAST:event_cbMunicipioItemStateChanged

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
        try {
             if(ValidarDados()){
                /// SetarObjetosComUI.
                 licencaDadosContratante2.setData(txtDataCadastro.getDate());
                 
                 Boolean bRet=false;
                 if(licencaDadosContratante2.getIdcontratante()==null){
                    bRet = GerenciadorLicenca.Contratante_Incluir(licencaDadosContratante2, 0, 0);
                 }else{
                    bRet = GerenciadorLicenca.Contratante_Editar(licencaDadosContratante2);
                 }
                 if (bRet){                     
                    MetodosUI_Auxiliares.MensagemAoUsuarioSimplesINFO(null,"PROCEDIMENTO REALIZADO COM SUCESSO",getTitle());
                    MetodosUI_Auxiliares.LimparCamposTexto(jPanel1);
                    this.dispose();
                 }else{
                    MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"NÃO FOI POSSÍVEL REALIZAR O PROCEDIMENTO",getTitle());
                 }
        
            }
            
        } catch (Exception e) {
              LogDinnamus.Log(e, true);
        }
      
    }//GEN-LAST:event_btIncluirActionPerformed

    private void txtDataCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataCadastroKeyPressed

        // TODO add your handling code here:         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {             btIncluirForma.requestFocus();          }     }//GEN-LAST:event_txtDataCadastroKeyPressed
    }
    private void txtCNPJ_CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCNPJ_CPFFocusGained

    }//GEN-LAST:event_txtCNPJ_CPFFocusGained

    private void opCPFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opCPFItemStateChanged
        // TODO add your handling code here:
        AtualizarMascara();
    }//GEN-LAST:event_opCPFItemStateChanged

    private void opCNPJItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opCNPJItemStateChanged
        // TODO add your handling code here:
        AtualizarMascara();
    }//GEN-LAST:event_opCNPJItemStateChanged

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void cbUFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbUFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbUFFocusLost

    private void cbMunicipioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbMunicipioFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_cbMunicipioFocusGained

    private void txtCNPJ_CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCNPJ_CPFFocusLost
        // TODO add your handling code here:
        try {
            
            if(contratante.getIdcontratante()==null){
                if(txtCNPJ_CPF.getText().matches("[\\d].*")){
                    if(GerenciadorLicenca.Contratante_Localizar(txtCNPJ_CPF.getText())){
                        MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null, "O DOCUMENTO INFORMADO ESTÁ SENDO USANDO POR OUTRO CONTRATANTE", getTitle());
                        txtCNPJ_CPF.setValue(null);
                        txtCNPJ_CPF.requestFocus();                        
                    }
                }
            }
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_txtCNPJ_CPFFocusLost
    
 private void AtualizarMascara(){
     try {
         
         if(opCPF.isSelected()){             
             txtCNPJ_CPF.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("###.###.###-##")));
         }else if(opCNPJ.isSelected()){
         
             txtCNPJ_CPF.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##.###.###/####-##")));         
         }
          
         txtCNPJ_CPF.setFocusLostBehavior(JFormattedTextField.COMMIT);          
         txtCNPJ_CPF.requestFocus();
     } catch (Exception e) {
            LogDinnamus.Log(e, true);
     }
 }
private boolean ValidarDados(){
    try {
        
        
        if (!Validacoes.ValidarCNPJ_Ou_CPF(txtCNPJ_CPF.getText())){
           MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(processamento,"CNPJ/CPF inválido",getTitle());
           return false;
        }
        if(txtMunicipio.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(processamento,"INFORME O MUNICÍPIO",getTitle());
          return false;
        }
        if(txtNome.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(processamento,"INFORME O NOME",getTitle());
          return false;
        }
        
        if(txtEndereco.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(processamento,"INFORME O ENDEREÇO",getTitle());
          return false;
        }
        
        if(txtbairro.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(processamento,"INFORME O BAIRRO",getTitle());
          return false;
        }
        
        if(txtDataCadastro.getDateEditor().getDate()==null){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(processamento,"DATA DO CADASTRO INVÁLIDA",getTitle());
          return false;
        }
        
        return true;
    } catch (Exception e) {
        LogDinnamus.Log(e, true);
        return false;
}
}private void PesquisarMunicipios(){
try {
        if(cbUF.getSelectedItem()!="ESCOLHA A UF"){    
            final ItemLista i = (ItemLista)cbUF.getSelectedItem();
            if(i!=null){        
                
                InteracaoComUsuarioDuranteProcesso.ExibirMensagem("Novo contratante","Pesquisando Município");
                new Thread() {
                        @Override
                        public void run(){
                            try {
                                cbMunicipio.setEnabled(false); 
                                MetodosUI_Auxiliares.PreencherCombo(cbMunicipio, GerenciadorLicenca.UF_MunicipioListar(i.getDescricao()), "municipio", "codigo",true,"string","<<ESCOLHA O MUNICIPIO>>");                                
                                cbMunicipio.setSelectedIndex(0);
                                txtMunicipio.setText("");
                                cbMunicipio.setEnabled(true);                                
                            } catch (Exception e) {
                                LogDinnamus.Log(e, true);
                            }
                            InteracaoComUsuarioDuranteProcesso.FecharMensagem();
                        }            
                }.start();                
                cbMunicipio.update(cbMunicipio.getGraphics());                
            }else{
                cbMunicipio.setModel(new DefaultComboBoxModel());
            }
        }else{
                cbMunicipio.setModel(new DefaultComboBoxModel()); 
        }
    } catch (Exception e) {
           LogDinnamus.Log(e, true);
    }

}
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.entidades.LicencaDadosContratante DadosContratante;
    private javax.swing.JButton btFechar;
    private javax.swing.ButtonGroup btIdentificacao;
    private javax.swing.JButton btIncluir;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JComboBox cbUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private br.entidades.LicencaDadosContratante licencaDadosContratante2;
    private javax.swing.JRadioButton opCNPJ;
    private javax.swing.JRadioButton opCPF;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCNPJ_CPF;
    private javax.swing.JTextField txtCodigo;
    private com.toedter.calendar.JDateChooser txtDataCadastro;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtbairro;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
