/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import br.diversos.ConverterStringEmItemLista;
import br.GerenciadorLicenca;
import br.diversos.Validacoes;
import br.cep.CepUtil;
import br.cep.Logradouro;
import br.com.log.LogDinnamus;
import br.com.ui.InteracaoComUsuarioDuranteProcesso;
import br.com.ui.ItemLista;
import br.com.ui.MetodosUI_Auxiliares;
import br.entidades.LicencaRepresentante;
import br.ui.teclas.controleteclas;
import com.toedter.calendar.JDateChooser;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Fernando
 */
public class frmRepresentantes extends javax.swing.JDialog {

    /**
     * Creates new form frmRepresentantes
     */
    boolean bRecarregarComponentes =true;
    private int idRepresentante=0;
    private LicencaRepresentante rep = new LicencaRepresentante();
    private String cSalvaCEP ="";
    public frmRepresentantes(java.awt.Frame parent, boolean modal,int idRepresentante) {
        super(parent, modal);
        this.idRepresentante = idRepresentante;
        if(idRepresentante>0){
            rep = GerenciadorLicenca.Representante_Pesquisar(idRepresentante);
        }
        initComponents();
        setLocationRelativeTo(null);
        
        controleteclas.TRocarTabPorEnter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        licencaRepresentante2 = rep;
        buttonGroup1 = new javax.swing.ButtonGroup();
        cbStatus = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNum = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtMunicipio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbUF = new javax.swing.JComboBox();
        cbMunicipio = new javax.swing.JComboBox();
        txtDataCadastro = new JDateChooser("dd/MM/yyyy", "##/##/####", '_');
        opCPF = new javax.swing.JRadioButton();
        opCNPJ = new javax.swing.JRadioButton();
        txtCNPJ_CPF = new javax.swing.JFormattedTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOBS = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        txtComissao = new javax.swing.JTextField();
        cbStatus1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btIncluir = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "EXPIRADO", "CANCELADO" }));

        jLabel11.setText("STATUS");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPRESENTANTES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("CODIGO");

        jLabel3.setText("NOME");

        jLabel4.setText("ENDEREÇO");

        jLabel5.setText("NUMERO");

        jLabel6.setText("BAIRRO");

        jLabel7.setText("MUNICIPIO");

        jLabel9.setText("CEP");

        jLabel10.setText("DT.CADASTRO");

        txtCodigo.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${idrepresentante}"), txtCodigo, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${razao}"), txtNome, org.jdesktop.beansbinding.BeanProperty.create("text"), "razao");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${cep}"), txtCEP, org.jdesktop.beansbinding.BeanProperty.create("text"), "cep");
        bindingGroup.addBinding(binding);

        txtCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCEPFocusLost(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${endereco}"), txtEndereco, org.jdesktop.beansbinding.BeanProperty.create("text"), "endereco");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${numero}"), txtNum, org.jdesktop.beansbinding.BeanProperty.create("text"), "numero");
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${bairro}"), txtbairro, org.jdesktop.beansbinding.BeanProperty.create("text"), "bairro");
        bindingGroup.addBinding(binding);

        txtMunicipio.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${codmunicipio}"), txtMunicipio, org.jdesktop.beansbinding.BeanProperty.create("text"), "codmunicipio");
        bindingGroup.addBinding(binding);

        jLabel8.setText("UF");

        cbUF.setModel(new DefaultComboBoxModel<ItemLista>());

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${uf}"), cbUF, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"), "uf");
        binding.setConverter(new ConverterStringEmItemLista());
        bindingGroup.addBinding(binding);

        cbUF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbUFItemStateChanged(evt);
            }
        });
        cbUF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbUFFocusLost(evt);
            }
        });

        cbMunicipio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMunicipioItemStateChanged(evt);
            }
        });
        cbMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbMunicipioFocusGained(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${dtcadastro}"), txtDataCadastro, org.jdesktop.beansbinding.BeanProperty.create("date"));
        bindingGroup.addBinding(binding);

        txtDataCadastro.getDateEditor().getUiComponent().addKeyListener(

            new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {}

                @Override
                public void keyPressed(KeyEvent e) {
                    if(e.getKeyCode()==KeyEvent.VK_ENTER){
                        txtOBS.requestFocus();
                    }
                }
                @Override
                public void keyReleased(KeyEvent e) {}

            }
        );
        txtDataCadastro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataCadastroKeyPressed(evt);
            }
        });

        buttonGroup1.add(opCPF);
        opCPF.setSelected(true);
        opCPF.setText("CPF");
        opCPF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opCPFItemStateChanged(evt);
            }
        });

        buttonGroup1.add(opCNPJ);
        opCNPJ.setText("CNPJ");
        opCNPJ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opCNPJItemStateChanged(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${cnpj}"), txtCNPJ_CPF, org.jdesktop.beansbinding.BeanProperty.create("value"), "cnpj");
        bindingGroup.addBinding(binding);

        txtCNPJ_CPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCNPJ_CPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCNPJ_CPFFocusLost(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${email}"), txtEmail, org.jdesktop.beansbinding.BeanProperty.create("text"), "email");
        bindingGroup.addBinding(binding);

        jLabel12.setText("COMISSÃO");

        jLabel13.setText("OBS");

        txtOBS.setColumns(20);
        txtOBS.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${obs}"), txtOBS, org.jdesktop.beansbinding.BeanProperty.create("text"), "obs");
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(txtOBS);

        jLabel14.setText("EMAIL");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${comissao}"), txtComissao, org.jdesktop.beansbinding.BeanProperty.create("text"), "comissao");
        bindingGroup.addBinding(binding);

        cbStatus1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ATIVO", "DESLIGADO" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, licencaRepresentante2, org.jdesktop.beansbinding.ELProperty.create("${status}"), cbStatus1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"), "status");
        bindingGroup.addBinding(binding);

        jLabel15.setText("STATUS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(opCPF)
                        .addGap(4, 4, 4)
                        .addComponent(opCNPJ)
                        .addGap(2, 2, 2)
                        .addComponent(txtCNPJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(22, 22, 22)
                                .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbStatus1, 0, 357, Short.MAX_VALUE)
                            .addComponent(txtEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNPJ_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10))
                    .addComponent(txtDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btIncluir.setText("OK");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(btIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir)
                    .addComponent(btFechar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    public boolean IniciarUI(){
        try {            
            
            String cUF = licencaRepresentante2.getUf();
            String cCodMunicipio = licencaRepresentante2.getCodmunicipio();
            
            MetodosUI_Auxiliares.PreencherCombo(cbUF, GerenciadorLicenca.UF_Listar(), "nome", "codigo", false,"string","<<ESCOLHA UMA UF>>" );            
            if(licencaRepresentante2.getIdrepresentante()==null){                
                cbUF.setSelectedIndex(0);              
            }else{
                bRecarregarComponentes=false;
                MetodosUI_Auxiliares.SetarOpcaoCombo(cbUF, cUF);
                bRecarregarComponentes=true;
               // MetodosUI_Auxiliares.PreencherCombo(cbMunicipio, GerenciadorLicenca.UF_MunicipioListar(cbUF.getSelectedItem().toString()), "municipio", "codigo",true);                                                
                //MetodosUI_Auxiliares.SetarOpcaoCombo(cbMunicipio, cCodMunicipio);
                cbMunicipio_Popular(cbUF.getSelectedItem().toString(),cCodMunicipio);
                txtDataCadastro.setDate(licencaRepresentante2.getDtcadastro());                      
            }
            if(licencaRepresentante2.getIdrepresentante()==null){
                opCPF.requestFocus();                   
            }else{
                if(licencaRepresentante2.getCnpj().trim().length()==14){
                    opCPF.setSelected(true);
                }else{
                    opCNPJ.setSelected(true);
                }
                
            }    
            AtualizarMascara();
            
            
            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    private boolean  cbMunicipio_Popular(String cUF, String cValorPadrao){
        try {

            MetodosUI_Auxiliares.PreencherCombo(cbMunicipio, GerenciadorLicenca.UF_MunicipioListar(cUF), "municipio", "codigo",true);                                                
            if(!"".equals(cValorPadrao)){
                MetodosUI_Auxiliares.SetarOpcaoCombo_Model(cbMunicipio, cValorPadrao);
            }            
            return true;
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
            return false;
        }
    }
    private boolean ValidarDados(){
    try {
        
        
        if (!Validacoes.ValidarCNPJ_Ou_CPF(txtCNPJ_CPF.getText())){
           MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"CNPJ/CPF inválido",getTitle());
           return false;
        }
        if(txtMunicipio.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"INFORME O MUNICÍPIO",getTitle());
          return false;
        }
        if(txtNome.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"INFORME O NOME",getTitle());
          return false;
        }
        
        if(txtEndereco.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"INFORME O ENDEREÇO",getTitle());
          return false;
        }
        
        if(txtbairro.getText().length()==0){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"INFORME O BAIRRO",getTitle());
          return false;
        }
        
        if(txtDataCadastro.getDateEditor().getDate()==null){
          MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"DATA DO CADASTRO INVÁLIDA",getTitle());
          return false;
        }
        
        return true;
    } catch (Exception e) {
        LogDinnamus.Log(e, true);
        return false;
}
}private void PesquisarMunicipios(){
try {
        if(cbUF.getSelectedItem()!="ESCOLHA A UF"){    
            final ItemLista i = (ItemLista)cbUF.getSelectedItem();
            if(i!=null){        
                
                InteracaoComUsuarioDuranteProcesso.ExibirMensagem("Novo Representante","Pesquisando Município");
                new Thread() {
                        @Override
                        public void run(){
                            try {
                                cbMunicipio.setEnabled(false); 
                                MetodosUI_Auxiliares.PreencherCombo(cbMunicipio, GerenciadorLicenca.UF_MunicipioListar(i.getDescricao()), "municipio", "codigo",true,"string","<<ESCOLHA O MUNICIPIO>>");                                
                                cbMunicipio.setSelectedIndex(0);
                                txtMunicipio.setText("");
                                cbMunicipio.setEnabled(true);                                
                            } catch (Exception e) {
                                LogDinnamus.Log(e, true);
                            }
                            InteracaoComUsuarioDuranteProcesso.FecharMensagem();
                        }            
                }.start();                
                cbMunicipio.update(cbMunicipio.getGraphics());                
            }else{
                cbMunicipio.setModel(new DefaultComboBoxModel());
            }
        }else{
                cbMunicipio.setModel(new DefaultComboBoxModel()); 
        }
    } catch (Exception e) {
           LogDinnamus.Log(e, true);
    }

}
    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        // TODO add your handling code here:
        try {
            if(ValidarDados()){                
                licencaRepresentante2.setIdrepresentante(idRepresentante);
                boolean bRet = GerenciadorLicenca.Representante_Persistir(licencaRepresentante2, 0, 0);
                if (bRet){
                    MetodosUI_Auxiliares.MensagemAoUsuarioSimplesINFO(null,"PROCEDIMENTO REALIZADO COM SUCESSO",getTitle());
                    MetodosUI_Auxiliares.LimparCamposTexto(jPanel1);
                    this.dispose();
                }else{
                    MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null,"NÃO FOI POSSÍVEL REALIZAR O PROCEDIMENTO",getTitle());
                }
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }

    }//GEN-LAST:event_btIncluirActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void txtCNPJ_CPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCNPJ_CPFFocusLost
        // TODO add your handling code here:
        try {
            if(licencaRepresentante2.getIdrepresentante()==null){
                if(txtCNPJ_CPF.getText().matches("[\\d].*")){
                    if(GerenciadorLicenca.Representante_Localizar(txtCNPJ_CPF.getText())){
                        MetodosUI_Auxiliares.MensagemAoUsuarioSimplesAVISO(null, "O DOCUMENTO INFORMADO ESTÁ SENDO USANDO POR OUTRO REPRESENTANTE", getTitle());
                        txtCNPJ_CPF.setValue(null);
                        txtCNPJ_CPF.requestFocus();
                    }
                }
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_txtCNPJ_CPFFocusLost

    private void txtCNPJ_CPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCNPJ_CPFFocusGained

    }//GEN-LAST:event_txtCNPJ_CPFFocusGained

    private void opCNPJItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opCNPJItemStateChanged
        // TODO add your handling code here:
        AtualizarMascara();
    }//GEN-LAST:event_opCNPJItemStateChanged

    private void opCPFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opCPFItemStateChanged
        // TODO add your handling code here:
        AtualizarMascara();
    }//GEN-LAST:event_opCPFItemStateChanged

    private void txtDataCadastroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataCadastroKeyPressed

    }//GEN-LAST:event_txtDataCadastroKeyPressed

    private void cbMunicipioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbMunicipioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMunicipioFocusGained

    private void cbMunicipioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMunicipioItemStateChanged
        // TODO add your handling code here:
        try {

            ItemLista i =(ItemLista)cbMunicipio.getSelectedItem();
            if(i!=null){
                txtMunicipio.setText(i.getIndice().toString());
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_cbMunicipioItemStateChanged

    private void cbUFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbUFFocusLost
        // TODO add your handling code here:
        try {
            
             
            
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_cbUFFocusLost

    private void cbUFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbUFItemStateChanged
        // TODO add your handling code here:
        if(bRecarregarComponentes){
            PesquisarMunicipios();
        }
    }//GEN-LAST:event_cbUFItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(!IniciarUI()){
            MetodosUI_Auxiliares.MensagemAoUsuarioSimples(null, "Não foi possível iniciar a interface com usuário", this.getTitle(), "AVISO");
            dispose();       
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCEPFocusLost
        // TODO add your handling code here:
        if(!txtCEP.getText().equals(cSalvaCEP)){
            BuscarCEP();
        }
        
    }//GEN-LAST:event_txtCEPFocusLost
private void BuscarCEP(){
   try {
           if(txtCEP.getText().matches("[\\d].*")){
              if(MetodosUI_Auxiliares.MensagemAoUsuarioOpcoes_Sim_e_Nao(null, "DESEJA PESQUISAR O CEP ?", getTitle())==MetodosUI_Auxiliares.Sim()){
                  Logradouro l = CepUtil.Pesquisar(txtCEP.getText(),true);
                  if(l.getCEP()!=null){
                     txtEndereco.setText(l.getEndereco());
                     txtbairro.setText(l.getBairro());
                     bRecarregarComponentes=false;
                     MetodosUI_Auxiliares.SetarOpcaoCombo_Model(cbUF,l.getUF());
                     bRecarregarComponentes=true;
                     cbMunicipio_Popular(l.getUF(),l.getCodMunicipio());
                  }                          
              }                  
           }  
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
          
        }
} private void AtualizarMascara(){
     try {
         
         if(opCPF.isSelected()){             
             txtCNPJ_CPF.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("###.###.###-##")));
         }else if(opCNPJ.isSelected()){
         
             txtCNPJ_CPF.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("##.###.###/####-##")));         
         }
          
         txtCNPJ_CPF.setFocusLostBehavior(JFormattedTextField.COMMIT);          
         txtCNPJ_CPF.requestFocus();
     } catch (Exception e) {
            LogDinnamus.Log(e, true);
     }
 }
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btIncluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbMunicipio;
    private javax.swing.JComboBox cbStatus;
    private javax.swing.JComboBox cbStatus1;
    private javax.swing.JComboBox cbUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private br.entidades.LicencaRepresentante licencaRepresentante2;
    private javax.swing.JRadioButton opCNPJ;
    private javax.swing.JRadioButton opCPF;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCNPJ_CPF;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtComissao;
    private com.toedter.calendar.JDateChooser txtDataCadastro;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtMunicipio;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextArea txtOBS;
    private javax.swing.JTextField txtbairro;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
