/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ui;

import br.com.ecf.MetodosECF;
import br.com.log.LogDinnamus;
import br.com.ui.MetodosUI_Auxiliares_1;
import br.ui.teclas.TeclasDeAtalho;
import br.ui.teclas.controleteclas;
import br.valor.formatar.FormatarNumero;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author Fernando
 */
public class frmCadastrarAliquota extends javax.swing.JDialog {

    /**
     * Creates new form frmCadastrarPagto
     */
    public boolean OK =false;
    public frmCadastrarAliquota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtAliquota.requestFocus();
        controleteclas.UsarTeclaNaTrocaDeCampos(PainelCorpo, KeyEvent.VK_ENTER);
        IniciarUI();
    }
    private Action ESCAPE=null;
    private boolean IniciarUI(){
       
            ESCAPE = new  AbstractAction() {
            @Override  
            public void actionPerformed(ActionEvent e) {
                btFecharActionPerformed(e);
            }};    
            
            TeclasDeAtalho.DefinirFuncao_A_Tecla(PainelFormasPagtoVenda, ESCAPE, "ESCAPE");                          
            controleteclas.SetarTodosOsBotoes(this.getContentPane());
            return true;
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        PainelFormasPagtoVenda = new javax.swing.JPanel();
        PainelTopo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btFechar = new javax.swing.JButton();
        PainelBotoes = new javax.swing.JPanel();
        btEditarForma = new javax.swing.JButton();
        PainelCorpo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtAliquota = new javax.swing.JTextField();
        PainelTipoPagto = new javax.swing.JPanel();
        opISS = new javax.swing.JRadioButton();
        opICMS = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelFormasPagtoVenda.setBackground(new java.awt.Color(255, 255, 255));
        PainelFormasPagtoVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PainelFormasPagtoVenda.setLayout(new java.awt.GridBagLayout());

        PainelTopo.setBackground(new java.awt.Color(0, 0, 0));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("CADASTRAR ALÍQUOTA");
        lblTitulo.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.3;
        PainelTopo.add(lblTitulo, gridBagConstraints);

        btFechar.setBackground(new java.awt.Color(0, 0, 0));
        btFechar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ui/Shut down_16x16.png"))); // NOI18N
        btFechar.setMnemonic('x');
        btFechar.setToolTipText("");
        btFechar.setBorderPainted(false);
        btFechar.setOpaque(false);
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        btFechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btFecharKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        PainelTopo.add(btFechar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        PainelFormasPagtoVenda.add(PainelTopo, gridBagConstraints);

        PainelBotoes.setBackground(new java.awt.Color(0, 0, 0));

        btEditarForma.setBackground(new java.awt.Color(0, 0, 0));
        btEditarForma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditarForma.setForeground(new java.awt.Color(255, 255, 255));
        btEditarForma.setMnemonic('e');
        btEditarForma.setText("GRAVAR NO ECF");
        btEditarForma.setBorderPainted(false);
        btEditarForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarFormaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBotoesLayout = new javax.swing.GroupLayout(PainelBotoes);
        PainelBotoes.setLayout(PainelBotoesLayout);
        PainelBotoesLayout.setHorizontalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBotoesLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btEditarForma)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        PainelBotoesLayout.setVerticalGroup(
            PainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btEditarForma))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        PainelFormasPagtoVenda.add(PainelBotoes, gridBagConstraints);

        PainelCorpo.setBackground(new java.awt.Color(255, 255, 204));
        PainelCorpo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("%Percentual da Aliquota");

        txtAliquota.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAliquota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAliquotaFocusLost(evt);
            }
        });

        PainelTipoPagto.setBackground(new java.awt.Color(255, 255, 255));
        PainelTipoPagto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE ALIQUOTA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        PainelTipoPagto.setOpaque(false);

        opISS.setBackground(new java.awt.Color(255, 255, 255));
        opISS.setText("ISS");
        opISS.setOpaque(false);

        opICMS.setBackground(new java.awt.Color(255, 255, 255));
        opICMS.setSelected(true);
        opICMS.setText("ICMS");
        opICMS.setOpaque(false);

        javax.swing.GroupLayout PainelTipoPagtoLayout = new javax.swing.GroupLayout(PainelTipoPagto);
        PainelTipoPagto.setLayout(PainelTipoPagtoLayout);
        PainelTipoPagtoLayout.setHorizontalGroup(
            PainelTipoPagtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTipoPagtoLayout.createSequentialGroup()
                .addComponent(opICMS)
                .addGap(31, 31, 31)
                .addComponent(opISS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelTipoPagtoLayout.setVerticalGroup(
            PainelTipoPagtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelTipoPagtoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PainelTipoPagtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opISS)
                    .addComponent(opICMS))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout PainelCorpoLayout = new javax.swing.GroupLayout(PainelCorpo);
        PainelCorpo.setLayout(PainelCorpoLayout);
        PainelCorpoLayout.setHorizontalGroup(
            PainelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCorpoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(PainelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(PainelTipoPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelCorpoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        PainelCorpoLayout.setVerticalGroup(
            PainelCorpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelCorpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAliquota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelTipoPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        PainelFormasPagtoVenda.add(PainelCorpo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelFormasPagtoVenda, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        try {
            dispose();
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
    }//GEN-LAST:event_btFecharActionPerformed

    private void btFecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btFecharKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFecharKeyPressed

    private void btEditarFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarFormaActionPerformed
        
        try {
            String Aliqouta = txtAliquota.getText();
            float PercAliquota = FormatarNumero.FormatarNumero(Aliqouta);
            if(PercAliquota==Float.NaN){
                MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "ALIQUOTA INFORMADA INVÁLIDA", "CADASTRAR ALIQUOTA");
                return;
            }    
            if(PercAliquota<1f || PercAliquota >99f){
              MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "ALIQUOTA INFORMADA PRECISA ESTAR ENTRE 1-99%", "CADASTRAR ALIQUOTA");
              return; 
            }
            if(!opICMS.isSelected() && !opISS.isSelected()){
               MetodosUI_Auxiliares_1.MensagemAoUsuarioSimplesAVISO(null, "ESCOLHA O TIPO DE ALÍQUOTA", lblTitulo.getText());
               return;
            }
        } catch (Exception e) {
            LogDinnamus.Log(e, true);
        }
        OK=true;
        dispose(); 
        
        
    }//GEN-LAST:event_btEditarFormaActionPerformed

    private void txtAliquotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAliquotaFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAliquotaFocusLost

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBotoes;
    private javax.swing.JPanel PainelCorpo;
    private javax.swing.JPanel PainelFormasPagtoVenda;
    private javax.swing.JPanel PainelTipoPagto;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JButton btEditarForma;
    private javax.swing.JButton btFechar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo;
    public javax.swing.JRadioButton opICMS;
    public javax.swing.JRadioButton opISS;
    public javax.swing.JTextField txtAliquota;
    // End of variables declaration//GEN-END:variables
}
