/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smack.config;

/**
 *
 * @author DSWM
 */
public class NovoJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NovoJDialog
     */
    public NovoJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblUsuario = new javax.swing.JLabel();
        lblQtMensagemNaoLidas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mensagem = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smack/ui/icons8-usuário-30.png"))); // NOI18N
        lblUsuario.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblUsuario, gridBagConstraints);

        lblQtMensagemNaoLidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQtMensagemNaoLidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtMensagemNaoLidas.setText("99:99");
        lblQtMensagemNaoLidas.setToolTipText("");
        lblQtMensagemNaoLidas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(lblQtMensagemNaoLidas, gridBagConstraints);

        Mensagem.setColumns(20);
        Mensagem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        Mensagem.setLineWrap(true);
        Mensagem.setRows(3);
        Mensagem.setText("MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO     MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO     MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO    MENSAGEM DE FERNANDO");
        Mensagem.setWrapStyleWord(true);
        Mensagem.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        Mensagem.setOpaque(false);
        jScrollPane1.setViewportView(Mensagem);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovoJDialog dialog = new NovoJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Mensagem;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblQtMensagemNaoLidas;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
