package br.ui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmProgresso.java
 *
 * Created on 12/08/2013, 14:40:44
 */


/**
 *
 * @author Fernando
 */
public class frmProgresso extends javax.swing.JDialog {

    /** Creates new form frmProgresso */
    public frmProgresso() {
        initComponents();
    }
        
    public void IniciarUI(String cMsg, int nMinimo, int nMaximo, boolean  bPosiciona){
            initComponents();
            if(!bPosiciona){
                this.setLocationRelativeTo(null);
            }else{                
                int nPosX =  Double.valueOf(java.awt.Toolkit.getDefaultToolkit().getScreenSize().getHeight()).intValue();
                int nPosY = Double.valueOf(java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth()).intValue()  ;
                this.setLocation(nPosX/2 - this.getHeight()/2 , nPosY/2);
            }
            this.setTitle(cMsg);
            lblMensagem.setText(cMsg);
            jProgressBar1.setMinimum(nMinimo);
            jProgressBar1.setMaximum(nMaximo);
            jProgressBar1.requestFocus();
    }
    public void Atualizar(int nValor, String cTexto)
    {
        jProgressBar1.setValue(nValor);
        
        lblMensagem.setText(cTexto);
        
    }
    public void InicializarSubBarraProgresso(int nMinimo, int nMaximo)
    {
        
       // jProgressBar2.setMinimum(nMinimo);
        //jProgressBar2.setMaximum(nMaximo);
        //jProgressBar2.update(this.getGraphics());        
    }
    public void InicializarBarraProgresso(int nMinimo, int nMaximo)
    {
        
        
        jProgressBar1.setMinimum(nMinimo);
        jProgressBar1.setMaximum(nMaximo);
        
        
    }
    public void AtualizarSubBarra(final int nValor, final String cTexto)
    {        
      // jProgressBar2.setValue(nValor);
       //lblMensagem1.setText(cTexto);
       this.update(this.getGraphics());
              
           
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PainelTopo = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        PainelCorpo = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 100));
        setMinimumSize(new java.awt.Dimension(400, 100));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 100));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        PainelTopo.setBackground(new java.awt.Color(0, 0, 0));
        PainelTopo.setLayout(new java.awt.GridBagLayout());

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("MENSAGEM");
        lblMensagem.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 7, 0);
        PainelTopo.add(lblMensagem, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        getContentPane().add(PainelTopo, gridBagConstraints);

        PainelCorpo.setBackground(new java.awt.Color(255, 255, 204));
        PainelCorpo.setLayout(new java.awt.GridBagLayout());

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(12, 10, 12, 10);
        PainelCorpo.add(jProgressBar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(PainelCorpo, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelCorpo;
    private javax.swing.JPanel PainelTopo;
    private javax.swing.JProgressBar jProgressBar1;
    public javax.swing.JLabel lblMensagem;
    // End of variables declaration//GEN-END:variables
}
